export interface MenuItem {
  id: string
  name: string
  description: string
  price: number
  category: string
  image: string
  ingredients: string[]
  allergens: string[]
  dietary: string[] // vegetarian, vegan, gluten-free, etc.
  spiceLevel?: number // 1-5 scale
  calories?: number
  prepTime: string
  chef_special?: boolean
  popular?: boolean
  seasonal?: boolean
}

export interface MenuCategory {
  id: string
  name: string
  description: string
  icon: string
}

export const menuCategories: MenuCategory[] = [
  { id: "recommended", name: "Recomendado para Hoy", description: "Sugerencias especiales de nuestro chef", icon: "⭐" },
  { id: "appetizers", name: "Entradas", description: "Perfectas para comenzar tu comida", icon: "🥗" },
  { id: "soups", name: "Sopas y Cremas", description: "Opciones frescas y nutritivas", icon: "🥣" },
  { id: "salads", name: "Ensaladas", description: "Creaciones frescas y saludables", icon: "🥬" },
  { id: "mains", name: "Platos de Autor", description: "Nuestros platos estrella", icon: "🍽️" },
  { id: "seafood", name: "Mariscos", description: "Lo mejor del océano", icon: "🐟" },
  { id: "steaks", name: "Carnes y Parrilla", description: "Cortes premium y especialidades a la parrilla", icon: "🥩" },
  { id: "pasta", name: "Pastas y Risottos", description: "Clásicos de inspiración italiana", icon: "🍝" },
  { id: "pizzas", name: "Pizzas", description: "Pizzas a la piedra con ingredientes frescos", icon: "🍕" },
  { id: "sandwiches", name: "Sándwiches y Fajitas", description: "Opciones contundentes y sabrosas", icon: "🥪" },
  { id: "sharing", name: "Tablas para Compartir", description: "Ideales para disfrutar en grupo", icon: "🍱" },
  { id: "kids", name: "Menú de Niños", description: "Platos pensados para los más pequeños", icon: "🧒" },
  { id: "breakfast", name: "Desayunos", description: "Para empezar el día con energía", icon: "🍳" },
  { id: "desserts", name: "Repostería y Pastelería", description: "Dulces finales para tu comida", icon: "🍰" },
  { id: "coffee", name: "Cafetería", description: "Café de grano, tés e infusiones", icon: "☕" },
  { id: "beverages", name: "Bebestibles y Jugos", description: "Refrescos y bebidas sin alcohol", icon: "🥤" },
  { id: "cocktails", name: "Cócteles", description: "Tragos y cócteles artesanales", icon: "🍹" },
  { id: "beers", name: "Cervezas y Shop", description: "Una selección de cervezas artesanales y de barril", icon: "🍺" },
  { id: "wines", name: "Vinos y Destilados", description: "Nuestra selección de vinos y licores", icon: "🍷" },
]

export const menuData = {
  location1: [
    // RECOMENDADO PARA HOY
    {
      id: "tomahawk-lomo-vetado",
      name: "Tomahawk de lomo vetado",
      description: "Tomahawk vetado de 700 grs, con suaves y jugosos tomates cherrys glaseados en toques de romero y ajo, vegetal asado de la estación, acompañado de papas a las finas hierbas, salsa de merkén y chimichurri que aporta mayor sabor ahumado a la carne. El Maridaje perfecto para este corte de carne es de la Viña la Quirigua, Vino Pajo premier cru, del Valle de Cachapoal zona de Curicó, Cabernet Sauvignon.",
      price: 24500,
      category: "recommended",
      image: "https://images.unsplash.com/photo-1594041682143-70634621c65a?w=500&h=400&fit=crop",
      ingredients: ["Lomo vetado Tomahawk", "Tomates cherry", "Romero", "Ajo", "Vegetales de estación", "Papas", "Merkén", "Chimichurri"],
      allergens: [],
      dietary: [],
      calories: 1200,
      prepTime: "30-35 min",
      chef_special: true,
      popular: true,
    },
    {
      id: "anticuchos-parrilleros",
      name: "Anticuchos Parrilleros",
      description: "Anticuchos grillados de res, cerdo y longaniza Llanquihue de 1000 grs, suaves y jugosos tomates cherrys glaseados en toques de romero y ajo, acompañado de papas a las finas hierbas, salsa de ajo con cilantro, tostadas de la casa y chimichurri que aporta mayor sabor ahumado a las carnes.",
      price: 26500,
      category: "recommended",
      image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=500&h=400&fit=crop",
      ingredients: ["Carne de res", "Carne de cerdo", "Longaniza Llanquihue", "Tomates cherry", "Papas", "Ajo", "Cilantro", "Pan tostado"],
      allergens: ["Gluten"],
      dietary: [],
      calories: 1500,
      prepTime: "25-30 min",
      chef_special: true,
      popular: true,
    },
    {
      id: "pastel-jaiba-500",
      name: "Pastel de Jaiba 500 grs",
      description: "Pastel de jaiba grande",
      price: 12500,
      category: "recommended",
      image: "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?w=500&h=400&fit=crop",
      ingredients: ["Jaiba", "Queso mantecoso", "Pan", "Crema", "Vino blanco"],
      allergens: ["Mariscos", "Lácteos", "Gluten"],
      dietary: [],
      calories: 650,
      prepTime: "20-25 min",
    },
    {
      id: "ravioles-salmon",
      name: "Ravioles relleno Salmón",
      description: "Ravioles rellenos de salmón en suave salsa de camarones y tomate cherry",
      price: 14900,
      category: "recommended",
      image: "https://images.unsplash.com/photo-1621996346565-e326e22e3e20?w=500&h=400&fit=crop",
      ingredients: ["Pasta de ravioles", "Salmón", "Camarones", "Tomate cherry", "Crema"],
      allergens: ["Pescado", "Mariscos", "Gluten", "Lácteos"],
      dietary: [],
      calories: 700,
      prepTime: "18-22 min",
    },
    {
      id: "crudo",
      name: "Crudo",
      description: "Suave corte de res, Cebolla morada, Pepinillo y Ají verde en bronoise, cilantro, gajos de Limón, tostadas y salsa de sour cream de la casa.",
      price: 11900,
      category: "recommended",
      image: "https://images.unsplash.com/photo-1639108398467-b76igha67ghas?w=500&h=400&fit=crop", // Placeholder
      ingredients: ["Carne de res", "Cebolla morada", "Pepinillo", "Ají verde", "Cilantro", "Limón", "Pan tostado", "Sour cream"],
      allergens: ["Gluten", "Lácteos"],
      dietary: [],
      calories: 450,
      prepTime: "10-12 min",
    },
    {
      id: "ramazzotti-violeta",
      name: "Ramazzotti violeta",
      description: "Una refrescante combinación de Ramazzotti Violetto, tónica y una rodaja de limón. Ideal para un aperitivo floral y vibrante.",
      price: 6500,
      category: "recommended",
      image: "https://images.unsplash.com/photo-1629426955728-8f3c179b5d63?w=500&h=400&fit=crop",
      ingredients: ["Ramazzotti Violetto", "Agua tónica", "Limón"],
      allergens: [],
      dietary: [],
      calories: 180,
      prepTime: "3-5 min",
      popular: true,
    },
    {
      id: "caipirina",
      name: "Caipiriña",
      description: "El clásico cóctel brasileño con cachaça, azúcar y limones frescos macerados para liberar todo su sabor.",
      price: 4500,
      category: "recommended",
      image: "https://images.unsplash.com/photo-1502636284198-543883a42a0b?w=500&h=400&fit=crop",
      ingredients: ["Cachaça", "Azúcar", "Limón"],
      allergens: [],
      dietary: [],
      calories: 230,
      prepTime: "5-7 min",
    },

    // CAFETERÍA
    {
      id: "tetera-compartir",
      name: "Tetera para compartir",
      description: "Tetera 750 ml, consultar variedades disponibles.",
      price: 4500,
      category: "coffee",
      image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=500&h=400&fit=crop",
      ingredients: ["Té a elección"],
      allergens: [],
      dietary: ["Vegano"],
      calories: 2,
      prepTime: "5-7 min",
    },
    {
      id: "tetera-pequena",
      name: "Tetera pequeña",
      description: "Tetera 500 ML, consultar variedades disponibles.",
      price: 2500,
      category: "coffee",
      image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=500&h=400&fit=crop",
      ingredients: ["Té a elección"],
      allergens: [],
      dietary: ["Vegano"],
      calories: 2,
      prepTime: "3-5 min",
    },
    {
      id: "te",
      name: "Té",
      description: "Té individual preparado con agua caliente",
      price: 1800,
      category: "coffee",
      image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500&h=400&fit=crop",
      ingredients: ["Té a elección"],
      allergens: [],
      dietary: ["Vegano"],
      calories: 2,
      prepTime: "3-5 min",
    },
    {
      id: "cafe-tradicional",
      name: "Café tradicional",
      description: "Café tradicional de filtro",
      price: 1800,
      category: "coffee",
      image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=500&h=400&fit=crop",
      ingredients: ["Café molido"],
      allergens: [],
      dietary: ["Vegano"],
      calories: 5,
      prepTime: "3-5 min",
    },
    {
      id: "expresso",
      name: "Expresso",
      description: "Un shot concentrado de nuestro café de grano premium, con un sabor intenso y una rica crema.",
      price: 2400,
      category: "coffee",
      image: "https://images.unsplash.com/photo-1579992305312-a892b51c1449?w=500&h=400&fit=crop",
      ingredients: ["Café de grano"],
      allergens: [],
      dietary: ["Vegano"],
      calories: 5,
      prepTime: "2-3 min",
    },
    {
      id: "expresso-doble",
      name: "Expresso doble",
      description: "Doble shot de espresso para un sabor más intenso",
      price: 3500,
      category: "coffee",
      image: "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=500&h=400&fit=crop",
      ingredients: ["Café de grano"],
      allergens: [],
      dietary: ["Vegano"],
      calories: 10,
      prepTime: "3-4 min",
    },
    {
      id: "americano",
      name: "Americano",
      description: "Espresso diluido con agua caliente para un sabor más suave",
      price: 2800,
      category: "coffee",
      image: "https://images.unsplash.com/photo-1459257831348-f0cdd359235f?w=500&h=400&fit=crop",
      ingredients: ["Café de grano", "Agua"],
      allergens: [],
      dietary: ["Vegano"],
      calories: 5,
      prepTime: "3-5 min",
    },
    {
      id: "ristretto",
      name: "Ristretto",
      description: "Un espresso más concentrado y corto para un sabor más fuerte",
      price: 2200,
      category: "coffee",
      image: "https://images.unsplash.com/photo-1549788938-3ee675e3b1a4?w=500&h=400&fit=crop",
      ingredients: ["Café de grano"],
      allergens: [],
      dietary: ["Vegano"],
      calories: 5,
      prepTime: "2-3 min",
    },
    {
      id: "mocaccino",
      name: "Mocaccino",
      description: "La perfecta combinación de espresso, chocolate y leche vaporizada",
      price: 3200,
      category: "coffee",
      image: "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=500&h=400&fit=crop",
      ingredients: ["Café de grano", "Chocolate", "Leche"],
      allergens: ["Lácteos"],
      dietary: [],
      calories: 180,
      prepTime: "4-6 min",
    },
    {
      id: "cafe-irlandes",
      name: "Café Irlandés",
      description: "Café con whisky irlandés, azúcar y crema batida",
      price: 4000,
      category: "coffee",
      image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=500&h=400&fit=crop",
      ingredients: ["Café de grano", "Whisky irlandés", "Azúcar", "Crema batida"],
      allergens: ["Lácteos"],
      dietary: [],
      calories: 200,
      prepTime: "5-7 min",
    },
    {
      id: "capuccino",
      name: "Capuccino",
      description: "El equilibrio perfecto entre espresso, leche vaporizada y una capa generosa de espuma de leche.",
      price: 3200,
      category: "coffee",
      image: "https://images.unsplash.com/photo-1557006094-43912a7a46b2?w=500&h=400&fit=crop",
      ingredients: ["Café de grano", "Leche"],
      allergens: ["Lácteos"],
      dietary: [],
      calories: 120,
      prepTime: "3-5 min",
    },
    {
      id: "cortado",
      name: "Cortado",
      description: "Espresso cortado con leche tibia para suavizar el sabor",
      price: 3200,
      category: "coffee",
      image: "https://images.unsplash.com/photo-1585339277861-2a4bab06c729?w=500&h=400&fit=crop",
      ingredients: ["Café de grano", "Leche"],
      allergens: ["Lácteos"],
      dietary: [],
      calories: 100,
      prepTime: "3-5 min",
    },
    {
      id: "chocolate-caliente",
      name: "Chocolate caliente",
      description: "Una bebida rica y reconfortante, hecha con chocolate de alta calidad y leche cremosa.",
      price: 2800,
      category: "coffee",
      image: "https://images.unsplash.com/photo-1604880892694-511d7a82914a?w=500&h=400&fit=crop",
      ingredients: ["Chocolate", "Leche", "Azúcar"],
      allergens: ["Lácteos"],
      dietary: [],
      calories: 250,
      prepTime: "5-7 min",
      popular: true,
    },
    {
      id: "chocolate-nevado",
      name: "Chocolate nevado",
      description: "Chocolate caliente con crema batida y cacao en polvo",
      price: 3500,
      category: "coffee",
      image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=500&h=400&fit=crop",
      ingredients: ["Chocolate", "Leche", "Crema batida", "Cacao en polvo"],
      allergens: ["Lácteos"],
      dietary: [],
      calories: 300,
      prepTime: "5-7 min",
    },
    {
      id: "cafe-helado",
      name: "Café helado",
      description: "Nuestro café de grano preparado en frío para un sabor suave y refrescante, servido con hielo.",
      price: 4000,
      category: "coffee",
      image: "https://images.unsplash.com/photo-1517701559435-560428511d10?w=500&h=400&fit=crop",
      ingredients: ["Café de grano", "Hielo", "Leche (opcional)"],
      allergens: ["Lácteos (opcional)"],
      dietary: [],
      calories: 90,
      prepTime: "5-7 min",
    },
    {
      id: "milkshake",
      name: "Milkshake",
      description: "Un batido cremoso y espeso, disponible en sabores de vainilla, chocolate o frutilla.",
      price: 4500,
      category: "coffee",
      image: "https://images.unsplash.com/photo-1626201344265-d14d4203d36b?w=500&h=400&fit=crop",
      ingredients: ["Helado", "Leche", "Sirope de sabor"],
      allergens: ["Lácteos"],
      dietary: [],
      calories: 450,
      prepTime: "5-7 min",
    },
    {
      id: "nutella-coffe",
      name: "Nutella Coffe",
      description: "Un capuccino cremoso con un toque irresistible de Nutella, perfecto para los amantes del chocolate y avellanas.",
      price: 3900,
      category: "coffee",
      image: "https://images.unsplash.com/photo-1582316523498-65113943346e?w=500&h=400&fit=crop",
      ingredients: ["Café espresso", "Leche", "Nutella"],
      allergens: ["Lácteos", "Frutos secos (avellanas)"],
      dietary: [],
      calories: 320,
      prepTime: "5-7 min",
    },
    {
      id: "infusion-menta-jengibre",
      name: "Infusión menta jengibre",
      description: "Infusión natural de menta y jengibre para una experiencia digestiva y refrescante",
      price: 1800,
      category: "coffee",
      image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500&h=400&fit=crop",
      ingredients: ["Menta", "Jengibre", "Agua"],
      allergens: [],
      dietary: ["Vegano"],
      calories: 5,
      prepTime: "5-7 min",
    },
    {
      id: "cafe-late",
      name: "Café Late",
      description: "Espresso con abundante leche vaporizada y una fina capa de espuma",
      price: 3200,
      category: "coffee",
      image: "https://images.unsplash.com/photo-1541167760496-1628856ab772?w=500&h=400&fit=crop",
      ingredients: ["Café espresso", "Leche"],
      allergens: ["Lácteos"],
      dietary: [],
      calories: 150,
      prepTime: "4-6 min",
    },
    {
      id: "afogato",
      name: "Afogato",
      description: "Porción helado de vainilla, con una carga de café de grano.",
      price: 3200,
      category: "coffee",
      image: "https://images.unsplash.com/photo-1579954115565-2964b5b0d614?w=500&h=400&fit=crop",
      ingredients: ["Helado de vainilla", "Café espresso"],
      allergens: ["Lácteos"],
      dietary: [],
      calories: 200,
      prepTime: "3-4 min",
    },
    {
      id: "caja-te-variedad",
      name: "Caja Té Infusiones Variedad",
      description: "Caja con selección de tés e infusiones variadas",
      price: 8000,
      category: "coffee",
      image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=500&h=400&fit=crop",
      ingredients: ["Té surtido", "Infusiones surtidas"],
      allergens: [],
      dietary: ["Vegano"],
      calories: 0,
      prepTime: "1 min",
    },
    {
      id: "lavazza-sachet",
      name: "Lavazza Sachet",
      description: "Café instantáneo premium Lavazza en sachets individuales",
      price: 2300,
      category: "coffee",
      image: "https://images.unsplash.com/photo-1595981267035-7b04ca84a82d?w=500&h=400&fit=crop",
      ingredients: ["Café instantáneo Lavazza"],
      allergens: [],
      dietary: ["Vegano"],
      calories: 5,
      prepTime: "2-3 min",
    },

    // BEBESTIBLES
    {
      id: "jugo-frambuesa",
      name: "Jugo Frambuesa",
      description: "Jugo natural de frambuesas frescas",
      price: 3600,
      category: "beverages",
      image: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=500&h=400&fit=crop",
      ingredients: ["Frambuesas", "Agua", "Azúcar (opcional)"],
      allergens: [],
      dietary: ["Vegano"],
      calories: 120,
      prepTime: "3-5 min",
    },
    {
      id: "limonada",
      name: "Limonada",
      description: "Refrescante limonada natural",
      price: 3900,
      category: "beverages",
      image: "https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=500&h=400&fit=crop",
      ingredients: ["Limón", "Agua", "Azúcar"],
      allergens: [],
      dietary: ["Vegano"],
      calories: 100,
      prepTime: "3-5 min",
    },
    {
      id: "limonada-menta-jengibre",
      name: "Limonada menta jengibre",
      description: "Una limonada refrescante y revitalizante con el toque fresco de la menta y el picante del jengibre.",
      price: 4200,
      category: "beverages",
      image: "https://images.unsplash.com/photo-1623364722522-6b3547e4f16a?w=500&h=400&fit=crop",
      ingredients: ["Limón", "Menta", "Jengibre", "Agua", "Azúcar"],
      allergens: [],
      dietary: ["Vegano"],
      calories: 110,
      prepTime: "5-7 min",
      popular: true,
    },
    {
      id: "agua-mineral-gas",
      name: "Agua mineral c/gas",
      description: "Agua mineral con gas refrescante",
      price: 2200,
      category: "beverages",
      image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=500&h=400&fit=crop",
      ingredients: ["Agua mineral", "Gas carbónico"],
      allergens: [],
      dietary: ["Vegano"],
      calories: 0,
      prepTime: "1 min",
    },
    {
      id: "red-bull",
      name: "Red Bull",
      description: "Bebida energética Red Bull",
      price: 3500,
      category: "beverages",
      image: "https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=500&h=400&fit=crop",
      ingredients: ["Cafeína", "Taurina", "Vitaminas del grupo B"],
      allergens: [],
      dietary: [],
      calories: 110,
      prepTime: "1 min",
    },
    {
      id: "crush",
      name: "Crush",
      description: "Bebida gaseosa sabor naranja",
      price: 2200,
      category: "beverages",
      image: "https://images.unsplash.com/photo-1541807084-8f0d8e0ffed6?w=500&h=400&fit=crop",
      ingredients: ["Agua carbonatada", "Concentrado de naranja", "Azúcar"],
      allergens: [],
      dietary: [],
      calories: 140,
      prepTime: "1 min",
    },
    {
      id: "sprite",
      name: "Sprite",
      description: "Bebida gaseosa de limón-lima",
      price: 2200,
      category: "beverages",
      image: "https://images.unsplash.com/photo-1541807084-8f0d8e0ffed6?w=500&h=400&fit=crop",
      ingredients: ["Agua carbonatada", "Concentrado de limón-lima", "Azúcar"],
      allergens: [],
      dietary: [],
      calories: 140,
      prepTime: "1 min",
    },
    {
      id: "ginger-ale",
      name: "Ginger Ale",
      description: "Bebida gaseosa con sabor a jengibre",
      price: 2200,
      category: "beverages",
      image: "https://images.unsplash.com/photo-1541807084-8f0d8e0ffed6?w=500&h=400&fit=crop",
      ingredients: ["Agua carbonatada", "Jengibre", "Azúcar"],
      allergens: [],
      dietary: [],
      calories: 130,
      prepTime: "1 min",
    },
    {
      id: "jugo-mango",
      name: "Jugo Mango",
      description: "Jugo natural de mango tropical",
      price: 3200,
      category: "beverages",
      image: "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=500&h=400&fit=crop",
      ingredients: ["Mango", "Agua"],
      allergens: [],
      dietary: ["Vegano"],
      calories: 130,
      prepTime: "3-5 min",
    },
    {
      id: "jugo-pina",
      name: "Jugo Piña",
      description: "Jugo natural de piña fresca",
      price: 3200,
      category: "beverages",
      image: "https://images.unsplash.com/photo-1587297931046-7e8b7ad97c73?w=500&h=400&fit=crop",
      ingredients: ["Piña", "Agua"],
      allergens: [],
      dietary: ["Vegano"],
      calories: 130,
      prepTime: "3-5 min",
    },
    {
      id: "coca-cola",
      name: "Coca Cola",
      description: "La clásica bebida gaseosa Coca-Cola",
      price: 2200,
      category: "beverages",
      image: "https:/ hoto-1561758033-d89a9ad46330?w=500&h=400&fit=crop",
      ingredients: ["Agua carbonatada", "Azúcar", "Concentrado de cola"],
      allergens: [],
      dietary: [],
      calories: 140,
      prepTime: "1 min",
    },
    {
      id: "coca-zero",
      name: "Coca Zero",
      description: "Coca-Cola sin azúcar con edulcorantes",
      price: 2200,
      category: "beverages",
      image: "https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=500&h=400&fit=crop",
      ingredients: ["Agua carbonatada", "Edulcorantes", "Concentrado de cola"],
      allergens: [],
      dietary: [],
      calories: 0,
      prepTime: "1 min",
    },
    {
      id: "agua-tonica",
      name: "Agua tónica",
      description: "Agua tónica con quinina",
      price: 2200,
      category: "beverages",
      image: "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=500&h=400&fit=crop",
      ingredients: ["Agua carbonatada", "Quinina", "Azúcar"],
      allergens: [],
      dietary: [],
      calories: 120,
      prepTime: "1 min",
    },
    {
      id: "agua-mineral-sin-gas",
      name: "Agua mineral s/gas",
      description: "Agua mineral natural sin gas",
      price: 2200,
      category: "beverages",
      image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=500&h=400&fit=crop",
      ingredients: ["Agua mineral"],
      allergens: [],
      dietary: ["Vegano"],
      calories: 0,
      prepTime: "1 min",
    },
    {
      id: "coca-cola-220",
      name: "Coca-cola 220 cc",
      description: "Coca-Cola en presentación pequeña",
      price: 1500,
      category: "beverages",
      image: "https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=500&h=400&fit=crop",
      ingredients: ["Agua carbonatada", "Azúcar", "Concentrado de cola"],
      allergens: [],
      dietary: [],
      calories: 90,
      prepTime: "1 min",
    },
    {
      id: "coca-zero-220",
      name: "Coca zero 220 cc",
      description: "Coca-Cola Zero en presentación pequeña",
      price: 1500,
      category: "beverages",
      image: "https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=500&h=400&fit=crop",
      ingredients: ["Agua carbonatada", "Edulcorantes", "Concentrado de cola"],
      allergens: [],
      dietary: [],
      calories: 0,
      prepTime: "1 min",
    },
    {
      id: "sprite-220",
      name: "Sprite 220 cc",
      description: "Sprite en presentación pequeña",
      price: 1500,
      category: "beverages",
      image: "https://images.unsplash.com/photo-1541807084-8f0d8e0ffed6?w=500&h=400&fit=crop",
      ingredients: ["Agua carbonatada", "Concentrado de limón-lima", "Azúcar"],
      allergens: [],
      dietary: [],
      calories: 90,
      prepTime: "1 min",
    },
    {
      id: "pepsi-220",
      name: "Pepsi 220 cc",
      description: "Pepsi en presentación pequeña",
      price: 1500,
      category: "beverages",
      image: "https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=500&h=400&fit=crop",
      ingredients: ["Agua carbonatada", "Azúcar", "Concentrado de cola"],
      allergens: [],
      dietary: [],
      calories: 90,
      prepTime: "1 min",
    },
    {
      id: "limonada-frambuesa",
      name: "Limonada Frambuesa",
      description: "La combinación perfecta entre lo ácido del limón y lo dulce de las frambuesas frescas.",
      price: 4200,
      category: "beverages",
      image: "https://images.unsplash.com/photo-1604329298292-62384a29a6a0?w=500&h=400&fit=crop",
      ingredients: ["Limón", "Frambuesa", "Agua", "Azúcar"],
      allergens: [],
      dietary: ["Vegano"],
      calories: 130,
      prepTime: "5-7 min",
    },
    {
      id: "jugo-frutilla",
      name: "Jugo de frutilla",
      description: "Jugo natural preparado con frutillas frescas de temporada, dulce y refrescante.",
      price: 3600,
      category: "beverages",
      image: "https://images.unsplash.com/photo-1542572533-3b036245133d?w=500&h=400&fit=crop",
      ingredients: ["Frutillas", "Agua", "Azúcar (opcional)"],
      allergens: [],
      dietary: ["Vegano"],
      calories: 140,
      prepTime: "5 min",
    },
    {
      id: "jugo-berries",
      name: "Jugo de Berries",
      description: "Frutilla, Arándanos y Frambuesas",
      price: 3600,
      category: "beverages",
      image: "https://images.unsplash.com/photo-1610422442225-c15e0735a468?w=500&h=400&fit=crop",
      ingredients: ["Frutilla", "Arándanos", "Frambuesas"],
      allergens: [],
      dietary: ["Vegano"],
      calories: 150,
      prepTime: "5 min",
    },
    {
      id: "sprite-cero",
      name: "Sprite Cero",
      description: "Sprite sin azúcar con edulcorantes",
      price: 2200,
      category: "beverages",
      image: "https://images.unsplash.com/photo-1541807084-8f0d8e0ffed6?w=500&h=400&fit=crop",
      ingredients: ["Agua carbonatada", "Edulcorantes", "Concentrado de limón-lima"],
      allergens: [],
      dietary: [],
      calories: 0,
      prepTime: "1 min",
    },
    {
      id: "manantial",
      name: "Manantial",
      description: "Agua sin Hielo",
      price: 0,
      category: "beverages",
      image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=500&h=400&fit=crop",
      ingredients: ["Agua"],
      allergens: [],
      dietary: ["Vegano"],
      calories: 0,
      prepTime: "1 min",
    },
    {
      id: "cordillerano",
      name: "Cordillerano",
      description: "Agua con hielo",
      price: 0,
      category: "beverages",
      image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=500&h=400&fit=crop",
      ingredients: ["Agua", "Hielo"],
      allergens: [],
      dietary: ["Vegano"],
      calories: 0,
      prepTime: "1 min",
    },
    {
      id: "ginger-ale-220",
      name: "Ginger Ale 220cc",
      description: "Ginger Ale en presentación pequeña",
      price: 1500,
      category: "beverages",
      image: "https://images.unsplash.com/photo-1541807084-8f0d8e0ffed6?w=500&h=400&fit=crop",
      ingredients: ["Agua carbonatada", "Jengibre", "Azúcar"],
      allergens: [],
      dietary: [],
      calories: 85,
      prepTime: "1 min",
    },
    {
      id: "tonica-220",
      name: "Tonica 220cc",
      description: "Agua tónica en presentación pequeña",
      price: 1500,
      category: "beverages",
      image: "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=500&h=400&fit=crop",
      ingredients: ["Agua carbonatada", "Quinina", "Azúcar"],
      allergens: [],
      dietary: [],
      calories: 80,
      prepTime: "1 min",
    },

    // REPOSTERÍA Y PASTELERÍA
    {
      id: "jardin-el-arbol",
      name: "Jardín el Árbol",
      description: "Volcán de chocolate 19% recubierto de azúcar glass, acompañado de mermelada de guinda, mini macarons, crocante de chocolate bitter, frutos rojos y sobre este, helado de vainilla.",
      price: 6200,
      category: "desserts",
      image: "https://images.unsplash.com/photo-1586985289936-a8a9352bd68e?w=500&h=400&fit=crop",
      ingredients: ["Chocolate", "Azúcar glass", "Mermelada de guinda", "Macarons", "Helado de vainilla"],
      allergens: ["Gluten", "Lácteos", "Huevos", "Frutos secos (almendras)"],
      dietary: [],
      calories: 750,
      prepTime: "15-18 min",
      chef_special: true,
    },
    {
      id: "pastel",
      name: "Pastel",
      description: "Pastel del día disponible",
      price: 4400,
      category: "desserts",
      image: "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=500&h=400&fit=crop",
      ingredients: ["Harina", "Azúcar", "Huevos", "Mantequilla"],
      allergens: ["Gluten", "Lácteos", "Huevos"],
      dietary: [],
      calories: 350,
      prepTime: "5 min",
    },
    {
      id: "tiramisu",
      name: "Tiramisú",
      description: "El clásico postre italiano, con capas de bizcocho empapado en café, crema de mascarpone y un toque de cacao.",
      price: 4300,
      category: "desserts",
      image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=500&h=400&fit=crop",
      ingredients: ["Bizcocho", "Café", "Queso mascarpone", "Huevos", "Cacao"],
      allergens: ["Gluten", "Lácteos", "Huevos"],
      dietary: [],
      calories: 450,
      prepTime: "10 min",
    },
    {
      id: "copa-helado-infantil",
      name: "Copa de Helado Infantil",
      description: "Copa de helado especial para niños",
      price: 4000,
      category: "desserts",
      image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=500&h=400&fit=crop",
      ingredients: ["Helado", "Decoraciones infantiles"],
      allergens: ["Lácteos"],
      dietary: [],
      calories: 300,
      prepTime: "5 min",
    },
    {
      id: "crepes-suzette",
      name: "Crêpes suzette",
      description: "Crêpes marinados en salsa de naranja y flambeado con Whisky.",
      price: 4100,
      category: "desserts",
      image: "https://images.unsplash.com/photo-1506084868230-bb9d95c24759?w=500&h=400&fit=crop",
      ingredients: ["Crêpes", "Salsa de naranja", "Whisky", "Azúcar"],
      allergens: ["Gluten", "Lácteos", "Huevos"],
      dietary: [],
      calories: 380,
      prepTime: "10-12 min",
    },
    {
      id: "panqueques-celestinos",
      name: "Panqueques Celestinos",
      description: "Panqueques tradicionales estilo celestinos",
      price: 4900,
      category: "desserts",
      image: "https://images.unsplash.com/photo-1506084868230-bb9d95c24759?w=500&h=400&fit=crop",
      ingredients: ["Panqueques", "Dulce de leche", "Crema"],
      allergens: ["Gluten", "Lácteos", "Huevos"],
      dietary: [],
      calories: 420,
      prepTime: "8-10 min",
    },
    {
      id: "copa-helado-3-sabores",
      name: "Copa de Helado 3 sabores",
      description: "Copa con helado de tres sabores a elección",
      price: 4500,
      category: "desserts",
      image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=500&h=400&fit=crop",
      ingredients: ["Helado de 3 sabores"],
      allergens: ["Lácteos"],
      dietary: [],
      calories: 450,
      prepTime: "5 min",
    },
    {
      id: "leche-asada",
      name: "Leche asada",
      description: "Postre tradicional chileno de leche asada al horno",
      price: 4200,
      category: "desserts",
      image: "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=500&h=400&fit=crop",
      ingredients: ["Leche", "Huevos", "Azúcar", "Canela"],
      allergens: ["Lácteos", "Huevos"],
      dietary: ["Sin gluten"],
      calories: 280,
      prepTime: "5 min",
    },
    {
      id: "volcan-chocolate",
      name: "Volcán de chocolate",
      description: "Volcán de chocolate 19% recubierto de azúcar glass, acompañado de mermelada de guinda, crocante de chocolate bitter, frutos rojos y sobre este, helado de vainilla.",
      price: 4900,
      category: "desserts",
      image: "https://images.unsplash.com/photo-1586985289936-a8a9352bd68e?w=500&h=400&fit=crop",
      ingredients: ["Chocolate", "Azúcar glass", "Mermelada de guinda", "Frutos rojos", "Helado de vainilla"],
      allergens: ["Gluten", "Lácteos", "Huevos"],
      dietary: [],
      calories: 550,
      prepTime: "12-15 min",
    },
    {
      id: "macarons-unidad",
      name: "Macarons Unidad",
      description: "Cremosos huevos revueltos acompañados de crujientes láminas de tocino, servido con tostadas.",
      price: 6500,
      category: "breakfast",
      image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=500&h=400&fit=crop",
      ingredients: ["Huevos", "Tocino", "Pan tostado"],
      allergens: ["Huevos", "Gluten"],
      dietary: [],
      calories: 480,
      prepTime: "10-12 min",
    },

    // ENTRADAS
    {
      id: "camarones-al-ajillo",
      name: "Camarones al Ajillo o al Pil Pil",
      description: "Camarones salteados en abundante ajo y aceite de oliva, con un toque de ají cacho de cabra para el pil pil.",
      price: 7900,
      category: "appetizers",
      image: "https://images.unsplash.com/photo-1605333241478-f0639d44332f?w=500&h=400&fit=crop",
      ingredients: ["Camarones", "Ajo", "Aceite de oliva", "Ají cacho de cabra (opcional)"],
      allergens: ["Mariscos"],
      dietary: [],
      spiceLevel: 2,
      calories: 350,
      prepTime: "12-15 min",
      popular: true,
    },
    {
      id: "ceviche-salmon",
      name: "Ceviche de Salmón",
      description: "Cubos de salmón fresco marinados en leche de tigre con cebolla morada, manzana verde, palta, pimentón y un toque de jengibre.",
      price: 6900,
      category: "appetizers",
      image: "https://images.unsplash.com/photo-1580959375497-c3b6b1b54a32?w=500&h=400&fit=crop",
      ingredients: ["Salmón", "Cebolla morada", "Manzana verde", "Palta", "Pimentón", "Jengibre", "Leche de tigre"],
      allergens: ["Pescado"],
      dietary: ["Sin gluten"],
      calories: 400,
      prepTime: "15 min",
    },
    
    // CARTA DE AUTOR
    {
      id: "plateada-braseada",
      name: "Plateada braseada con pastelera de choclo",
      description: "Plateada de vacuno cocinada lentamente en cerveza artesanal ámbar, servida sobre una cremosa pastelera de choclo.",
      price: 16500,
      category: "mains",
      image: "https://images.unsplash.com/photo-1626082894351-78b9b7d8c47f?w=500&h=400&fit=crop",
      ingredients: ["Plateada de vacuno", "Cerveza artesanal", "Pastelera de choclo", "Cebolla", "Zanahoria"],
      allergens: ["Gluten (en cerveza)"],
      dietary: [],
      calories: 850,
      prepTime: "35-40 min",
      chef_special: true,
    },
    {
      id: "salmon-gratinado",
      name: "Salmón gratinado",
      description: "Filete de salmón cubierto con queso gratinado, cebolla caramelizada y tomate confitado, acompañado de guarnición a elección.",
      price: 15500,
      category: "mains",
      image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=500&h=400&fit=crop",
      ingredients: ["Salmón", "Queso", "Cebolla caramelizada", "Tomate confitado"],
      allergens: ["Pescado", "Lácteos"],
      dietary: [],
      calories: 720,
      prepTime: "22-25 min",
    },
    {
      id: "osobuco-braseado",
      name: "Osobuco Braseado",
      description: "Osobuco cocinado lentamente en vino Carmenère hasta estar increíblemente tierno, servido con un cremoso risotto de champiñones.",
      price: 14000,
      category: "mains",
      image: "https://images.unsplash.com/photo-1604581101967-0f62d106180a?w=500&h=400&fit=crop",
      ingredients: ["Osobuco", "Vino Carmenère", "Risotto", "Champiñones"],
      allergens: ["Lácteos"],
      dietary: [],
      calories: 950,
      prepTime: "40-45 min",
    },

    // CORTES CON GUARNICIÓN
    {
      id: "lomo-premium-res",
      name: "Lomo premium de Res",
      description: "Un corte de lomo de res de alta calidad, cocinado al punto deseado y servido con la guarnición que prefieras.",
      price: 13900,
      category: "steaks",
      image: "https://images.unsplash.com/photo-1546964124-6cce46315223?w=500&h=400&fit=crop",
      ingredients: ["Lomo de res", "Sal", "Pimienta"],
      allergens: [],
      dietary: ["Sin gluten"],
      calories: 600,
      prepTime: "20-25 min",
    },
    
    // MENÚ DE NIÑOS
    {
      id: "nuggets-papas-fritas",
      name: "No lo sé",
      description: "Crujientes nuggets de pollo acompañados de papas fritas. ¡La opción segura para los pequeños!",
      price: 6800,
      category: "kids",
      image: "https://images.unsplash.com/photo-1626078298468-13c473a26989?w=500&h=400&fit=crop",
      ingredients: ["Nuggets de pollo", "Papas fritas"],
      allergens: ["Gluten"],
      dietary: [],
      calories: 450,
      prepTime: "10-12 min",
    },

    // VEGETARIANOS Y ENSALADAS
    {
      id: "ensalada-cesar-camaron",
      name: "Ensalada Cesar Camarón",
      description: "La clásica ensalada César con un giro marino: camarones salteados al ajillo, crutones, queso parmesano y aderezo césar.",
      price: 8900,
      category: "salads",
      image: "https://images.unsplash.com/photo-1580959375497-c3b6b1b54a32?w=500&h=400&fit=crop",
      ingredients: ["Mix de lechugas", "Camarones", "Crutones", "Queso parmesano", "Aderezo césar"],
      allergens: ["Mariscos", "Gluten", "Lácteos"],
      dietary: [],
      calories: 550,
      prepTime: "12-15 min",
    },

    // SÁNDWICH
    {
      id: "hamburguesa-golosa",
      name: "Hamburguesa Golosa",
      description: "Una hamburguesa que lo tiene todo: tocino, queso cheddar, cebolla caramelizada y un huevo frito, todo en pan brioche.",
      price: 8900,
      category: "sandwiches",
      image: "https://images.unsplash.com/photo-1605789535333-8a033c46a6b5?w=500&h=400&fit=crop",
      ingredients: ["Hamburguesa de res", "Tocino", "Queso cheddar", "Cebolla caramelizada", "Huevo", "Pan brioche"],
      allergens: ["Gluten", "Lácteos", "Huevos"],
      dietary: [],
      calories: 980,
      prepTime: "18-20 min",
      popular: true,
    },

    // TABLAS
    {
      id: "tabla-mar-tierra",
      name: "Tabla mar y tierra",
      description: "Una tabla para compartir con lo mejor de ambos mundos: salteado de res, pollo, champiñones, tomates cherry y langostinos, servida con papas fritas y salsas de la casa.",
      price: 26900,
      category: "sharing",
      image: "https://images.unsplash.com/photo-1604908176997-12c1537e96e4?w=500&h=400&fit=crop",
      ingredients: ["Carne de res", "Pollo", "Langostinos", "Champiñones", "Papas fritas"],
      allergens: ["Mariscos"],
      dietary: [],
      calories: 1800,
      prepTime: "25-30 min",
    },

    // PIZZAS
    {
      id: "pizza-todas-las-carnes",
      name: "Pizza Todas las carnes",
      description: "Para los amantes de la carne: res, pollo, cerdo, longaniza, tocino ahumado y queso fundido sobre nuestra masa a la piedra.",
      price: 15900,
      category: "pizzas",
      image: "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=500&h=400&fit=crop",
      ingredients: ["Masa de pizza", "Salsa pomodoro", "Queso mozzarella", "Res", "Pollo", "Cerdo", "Longaniza", "Tocino"],
      allergens: ["Gluten", "Lácteos"],
      dietary: [],
      calories: 1100,
      prepTime: "20-25 min",
    },

    // CERVEZAS Y SHOP
    {
      id: "kunstmann-torobayo",
      name: "Kunstmann Torobayo",
      description: "Una cerveza Pale Ale de color ámbar rojizo, con un equilibrio perfecto entre amargor y dulzor de la malta.",
      price: 4900,
      category: "beers",
      image: "https://images.unsplash.com/photo-1608270586620-248524c67de8?w=500&h=400&fit=crop",
      ingredients: ["Agua", "Malta de cebada", "Lúpulo", "Levadura"],
      allergens: ["Gluten"],
      dietary: [],
      calories: 200,
      prepTime: "1-2 min",
      popular: true,
    },

    // COCTELES
    {
      id: "pisco-sour-clasico",
      name: "Pisco Sour clásico",
      description: "El cóctel nacional en su máxima expresión: pisco, jugo de limón recién exprimido y un toque de goma.",
      price: 4000,
      category: "cocktails",
      image: "https://images.unsplash.com/photo-1586968034870-fc45d9471131?w=500&h=400&fit=crop",
      ingredients: ["Pisco", "Jugo de limón", "Goma", "Clara de huevo"],
      allergens: ["Huevos"],
      dietary: [],
      calories: 220,
      prepTime: "3-5 min",
      popular: true,
    },
    {
      id: "mojito-clasico",
      name: "Mojito clásico",
      description: "Un cóctel refrescante y veraniego con ron, menta fresca, limón de pica, azúcar y un toque de soda.",
      price: 5000,
      category: "cocktails",
      image: "https://images.unsplash.com/photo-1543364195-bfe6e49323d7?w=500&h=400&fit=crop",
      ingredients: ["Ron", "Menta", "Limón de pica", "Azúcar", "Soda"],
      allergens: [],
      dietary: [],
      calories: 180,
      prepTime: "5-7 min",
    },

    // VINOS
    {
      id: "casillero-diablo-reserva-privada",
      name: "Casillero del Diablo, Reserva Privada Cabernet Sauvignon",
      description: "Un vino tinto elegante y con cuerpo, con notas de frutos negros, cassis y un toque de vainilla por su paso por barrica.",
      price: 17900,
      category: "wines",
      image: "https://images.unsplash.com/photo-1584916201218-6e3a365bb454?w=500&h=400&fit=crop",
      ingredients: ["Uvas Cabernet Sauvignon"],
      allergens: [],
      dietary: ["Vegano"],
      calories: 125,
      prepTime: "1-2 min",
    },
  ],

  location2: [
    // Entradas
    {
      id: "bruschetta-jardin",
      name: "Bruschetta del Jardín",
      description: "Pan tostado con tomates heritage, albahaca y glaseado balsámico",
      price: 10990,
      category: "appetizers",
      image: "https://images.unsplash.com/photo-1572441713132-51c75654db73?w=500&h=400&fit=crop",
      ingredients: ["Pan artesanal", "Tomates heritage", "Albahaca fresca", "Glaseado balsámico", "Aceite de oliva"],
      allergens: ["Gluten"],
      dietary: ["Vegetariano", "Vegano"],
      calories: 180,
      prepTime: "8-10 min",
      seasonal: true,
    },
    {
      id: "carpaccio-betarraga",
      name: "Carpaccio de Betarraga",
      description: "Betarragas asadas en láminas finas con queso de cabra y nueces confitadas",
      price: 13990,
      category: "appetizers",
      image: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=500&h=400&fit=crop",
      ingredients: ["Betarragas asadas", "Queso de cabra", "Nueces confitadas", "Rúcula", "Vinagreta de miel"],
      allergens: ["Lácteos", "Frutos secos"],
      dietary: ["Vegetariano", "Sin gluten"],
      calories: 220,
      prepTime: "10-12 min",
      chef_special: true,
    },
    
    // Mariscos
    {
      id: "salmon-hierbas",
      name: "Salmón en Costra de Hierbas",
      description: "Salmón del Atlántico con hierbas del jardín y salsa de mantequilla al limón",
      price: 26990,
      category: "seafood",
      image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=500&h=400&fit=crop",
      ingredients: ["Salmón del Atlántico", "Hierbas frescas", "Mantequilla al limón", "Vegetales de estación"],
      allergens: ["Pescado", "Lácteos"],
      dietary: ["Sin gluten"],
      calories: 480,
      prepTime: "18-20 min",
      chef_special: true,
    },

    // Pastas y Risottos
    {
      id: "risotto-trufa",
      name: "Risotto de Trufa y Hongos",
      description: "Arroz carnaroli cremoso con hongos silvestres y aceite de trufa",
      price: 22990,
      category: "pasta",
      image: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=500&h=400&fit=crop",
      ingredients: ["Arroz carnaroli", "Hongos silvestres", "Aceite de trufa", "Parmesano", "Vino blanco"],
      allergens: ["Lácteos"],
      dietary: ["Vegetariano"],
      calories: 520,
      prepTime: "25-30 min",
      chef_special: true,
    },

    // Postres
    {
      id: "panna-cotta-lavanda",
      name: "Panna Cotta de Lavanda",
      description: "Postre sedoso con miel y frutos rojos frescos",
      price: 9990,
      category: "desserts",
      image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=500&h=400&fit=crop",
      ingredients: ["Crema", "Lavanda", "Miel", "Frutos rojos", "Menta"],
      allergens: ["Lácteos"],
      dietary: ["Vegetariano", "Sin gluten"],
      calories: 280,
      prepTime: "5 min",
      popular: true,
    },

    // Bebidas
    {
      id: "gin-botanico",
      name: "Gin Botánico",
      description: "Gin infusionado con hierbas frescas y flor de saúco",
      price: 11990,
      category: "cocktails",
      image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=500&h=400&fit=crop",
      ingredients: ["Gin infusionado", "Hierbas frescas", "Flor de saúco", "Pepino", "Tónica"],
      allergens: [],
      dietary: ["Vegano"],
      prepTime: "5-7 min",
      popular: true,
    },
  ],

  location3: [
    // Entradas
    {
      id: "tabla-mariscos",
      name: "Tabla de Mariscos Costeros",
      description: "Selección de ostras frescas, camarones y centolla con salsa cocktail",
      price: 38990,
      category: "appetizers",
      image: "https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?w=500&h=400&fit=crop",
      ingredients: ["Ostras frescas", "Camarones jumbo", "Centolla", "Salsa cocktail", "Limón"],
      allergens: ["Mariscos"],
      dietary: ["Sin gluten"],
      calories: 320,
      prepTime: "10-12 min",
      chef_special: true,
    },
    {
      id: "camarones-coco",
      name: "Camarones Apanados en Coco",
      description: "Camarones jumbo en costra de coco con chutney de mango",
      price: 17990,
      category: "appetizers",
      image: "https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=500&h=400&fit=crop",
      ingredients: ["Camarones jumbo", "Coco rallado", "Chutney de mango", "Salsa agridulce"],
      allergens: ["Mariscos", "Gluten"],
      dietary: [],
      calories: 380,
      prepTime: "12-15 min",
      popular: true,
    },

    // Sopas
    {
      id: "chupe-mariscos",
      name: "Chupe de Mariscos",
      description: "Sopa cremosa con almejas frescas, papas y hierbas",
      price: 13990,
      category: "soups",
      image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=500&h=400&fit=crop",
      ingredients: ["Almejas frescas", "Papas", "Crema", "Apio", "Cebollas", "Hierbas"],
      allergens: ["Mariscos", "Lácteos"],
      dietary: [],
      calories: 380,
      prepTime: "8-10 min",
      popular: true,
    },

    // Mariscos
    {
      id: "cioppino-costero",
      name: "Cioppino Costero",
      description: "Guiso de mariscos frescos con pan artesanal y hierbas",
      price: 29990,
      category: "seafood",
      image: "https://images.unsplash.com/photo-1559847844-5315695dadae?w=500&h=400&fit=crop",
      ingredients: ["Mariscos mixtos", "Caldo de tomate", "Pan artesanal", "Hierbas frescas", "Vino blanco"],
      allergens: ["Pescado", "Mariscos", "Gluten"],
      dietary: [],
      calories: 580,
      prepTime: "20-25 min",
      chef_special: true,
    },
    {
      id: "robalo-parrilla",
      name: "Robalo a la Parrilla",
      description: "Robalo mediterráneo con limón, hierbas y aceite de oliva",
      price: 27990,
      category: "seafood",
      image: "https://images.unsplash.com/photo-1544943910-4c1dc44aab44?w=500&h=400&fit=crop",
      ingredients: ["Robalo entero", "Limón", "Hierbas frescas", "Aceite de oliva extra virgen", "Sal marina"],
      allergens: ["Pescado"],
      dietary: ["Sin gluten"],
      calories: 420,
      prepTime: "15-18 min",
      popular: true,
    },
    {
      id: "sandwich-centolla",
      name: "Sándwich de Centolla",
      description: "Carne fresca de centolla en pan brioche con mayonesa al limón",
      price: 31990,
      category: "seafood",
      image: "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?w=500&h=400&fit=crop",
      ingredients: ["Centolla fresca", "Pan brioche", "Mayonesa al limón", "Apio", "Ciboulette"],
      allergens: ["Mariscos", "Gluten", "Lácteos", "Huevos"],
      dietary: [],
      calories: 520,
      prepTime: "12-15 min",
      chef_special: true,
    },

    // Carnes
    {
      id: "mar-tierra",
      name: "Mar y Tierra",
      description: "Filete a la parrilla con cola de langosta y mantequilla de ajo",
      price: 42990,
      category: "steaks",
      image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=500&h=400&fit=crop",
      ingredients: ["Filete mignon", "Cola de langosta", "Mantequilla de ajo", "Espárragos", "Puré de papas"],
      allergens: ["Mariscos", "Lácteos"],
      dietary: [],
      calories: 780,
      prepTime: "25-30 min",
      chef_special: true,
    },

    // Postres
    {
      id: "pie-limon",
      name: "Pie de Limón",
      description: "Postre tradicional con base de galleta y crema batida",
      price: 7990,
      category: "desserts",
      image: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=500&h=400&fit=crop",
      ingredients: ["Jugo de limón", "Base de galleta", "Leche condensada", "Crema batida", "Ralladura de limón"],
      allergens: ["Gluten", "Lácteos", "Huevos"],
      dietary: ["Vegetariano"],
      calories: 380,
      prepTime: "5 min",
      popular: true,
    },

    // Bebidas
    {
      id: "sangria-atardecer",
      name: "Sangría del Atardecer",
      description: "Vino tinto de la casa con frutas de estación y cítricos",
      price: 10990,
      category: "cocktails",
      image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=500&h=400&fit=crop",
      ingredients: ["Vino tinto", "Frutas de estación", "Cítricos", "Brandy", "Almíbar"],
      allergens: [],
      dietary: ["Vegano"],
      prepTime: "3-5 min",
      popular: true,
    },
  ],
}

// Helper function to find menu item by ID across all locations
export function findMenuItemById(itemId: string): MenuItem | null {
  for (const locationItems of Object.values(menuData)) {
    const item = locationItems.find((item) => item.id === itemId)
    if (item) return item
  }
  return null
}

// Helper function to get menu item ID by name (for backward compatibility)
export function getMenuItemIdByName(name: string, locationId: string): string | null {
  const locationItems = menuData[locationId as keyof typeof menuData]
  if (!locationItems) return null

  const item = locationItems.find((item) => item.name.toLowerCase() === name.toLowerCase())
  return item?.id || null
}
