import { MenuItem } from "./menu-data"

// Menu for Location 2: 1898
export const menuLocation2: MenuItem[] = [
  // Entradas
  {
    id: "bruschetta-jardin",
    name: "Bruschetta del Jardín",
    description: "Pan tostado con tomates heritage, albahaca y glaseado balsámico",
    price: 10990,
    category: "appetizers",
    image: "https://images.unsplash.com/photo-1572441713132-51c75654db73?w=500&h=400&fit=crop",
    ingredients: ["Pan artesanal", "Tomates heritage", "Albahaca fresca", "Glaseado balsámico", "Aceite de oliva"],
    allergens: ["Gluten"],
    dietary: ["vegetarian", "vegan"],
    calories: 180,
    prepTime: "8-10 min",
    seasonal: true,
  },
  {
    id: "carpaccio-betarraga",
    name: "Carpaccio de Betarraga",
    description: "Betarragas asadas en láminas finas con queso de cabra y nueces confitadas",
    price: 13990,
    category: "appetizers",
    image: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=500&h=400&fit=crop",
    ingredients: ["Betarragas asadas", "Queso de cabra", "Nueces confitadas", "Rúcula", "Vinagreta de miel"],
    allergens: ["Lácteos", "Frutos secos"],
    dietary: ["vegetarian", "gluten-free"],
    calories: 220,
    prepTime: "10-12 min",
    chef_special: true,
  },
  
  // Mariscos
  {
    id: "salmon-hierbas",
    name: "Salmón en Costra de Hierbas",
    description: "Salmón del Atlántico con hierbas del jardín y salsa de mantequilla al limón",
    price: 26990,
    category: "seafood",
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=500&h=400&fit=crop",
    ingredients: ["Salmón del Atlántico", "Hierbas frescas", "Mantequilla al limón", "Vegetales de estación"],
    allergens: ["Pescado", "Lácteos"],
    dietary: ["gluten-free"],
    calories: 480,
    prepTime: "18-20 min",
    chef_special: true,
  },

  // Pastas y Risottos
  {
    id: "risotto-trufa",
    name: "Risotto de Trufa y Hongos",
    description: "Arroz arbóreo con trufa negra, hongos silvestres y parmesano",
    price: 22990,
    category: "pasta",
    image: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=500&h=400&fit=crop",
    ingredients: ["Arroz arbóreo", "Trufa negra", "Hongos silvestres", "Parmesano", "Vino blanco"],
    allergens: ["Lácteos"],
    dietary: ["vegetarian", "gluten-free"],
    calories: 520,
    prepTime: "20-25 min",
    chef_special: true,
    seasonal: true,
  },
  {
    id: "gnocchi-espinaca",
    name: "Gnocchi de Espinaca",
    description: "Gnocchi caseros de espinaca con salsa de nueces y gorgonzola",
    price: 18990,
    category: "pasta",
    image: "https://images.unsplash.com/photo-1612450632008-22c2a5437dc1?w=500&h=400&fit=crop",
    ingredients: ["Gnocchi de espinaca", "Nueces", "Gorgonzola", "Crema", "Espinaca fresca"],
    allergens: ["Gluten", "Lácteos", "Frutos secos"],
    dietary: ["vegetarian"],
    calories: 580,
    prepTime: "15-18 min",
  },

  // Postres
  {
    id: "creme-brulee-lavanda",
    name: "Crème Brûlée de Lavanda",
    description: "Crema catalana con esencia de lavanda y azúcar caramelizada",
    price: 7990,
    category: "desserts",
    image: "https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?w=500&h=400&fit=crop",
    ingredients: ["Crema", "Huevos", "Lavanda", "Azúcar", "Vainilla"],
    allergens: ["Lácteos", "Huevos"],
    dietary: ["vegetarian", "gluten-free"],
    calories: 380,
    prepTime: "8-10 min",
    chef_special: true,
  },

  // Bebidas
  {
    id: "te-botanico",
    name: "Té Botánico del Jardín",
    description: "Infusión de hierbas del jardín con miel de lavanda",
    price: 4990,
    category: "beverages",
    image: "https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?w=500&h=400&fit=crop",
    ingredients: ["Hierbas frescas", "Miel de lavanda", "Agua purificada"],
    allergens: [],
    dietary: ["vegan", "gluten-free"],
    calories: 40,
    prepTime: "5-7 min",
    seasonal: true,
  },
  {
    id: "limonada-romero",
    name: "Limonada con Romero",
    description: "Limonada artesanal con jarabe de romero y hielo de pétalos",
    price: 5990,
    category: "beverages",
    image: "https://images.unsplash.com/photo-1523371054106-bbf80586c38c?w=500&h=400&fit=crop",
    ingredients: ["Limón", "Romero", "Azúcar de caña", "Agua con gas", "Pétalos comestibles"],
    allergens: [],
    dietary: ["vegan", "gluten-free"],
    calories: 120,
    prepTime: "5 min",
  },

  // Vinos
  {
    id: "vino-organico-valle",
    name: "Vino Orgánico del Valle",
    description: "Selección de vinos orgánicos de valles chilenos",
    price: 18990,
    category: "wines",
    image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=500&h=400&fit=crop",
    ingredients: ["Uvas orgánicas"],
    allergens: [],
    dietary: ["vegan"],
    calories: 125,
    prepTime: "2 min",
  },

  // Cócteles
  {
    id: "gin-garden",
    name: "Garden Gin Tonic",
    description: "Gin premium con tónica artesanal y botánicos del jardín",
    price: 8990,
    category: "cocktails",
    image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=500&h=400&fit=crop",
    ingredients: ["Gin premium", "Tónica artesanal", "Pepino", "Romero", "Enebro"],
    allergens: [],
    dietary: ["vegan", "gluten-free"],
    calories: 180,
    prepTime: "5-7 min",
    popular: true,
  },
]