import { MenuItem } from "./menu-data"

// Menu for Location 3: Capriccio - Coastal/Seafood theme
export const menucapriccio: MenuItem[] = [
  // Coctelería de Autor
  {
    id: "auguri",
    name: "Auguri",
    description: "Cóctel de autor con mezcla exclusiva de la casa",
    price: 6990,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1536935338788-846bb9981813?w=500&h=400&fit=crop",
    ingredients: ["Base de licor (ej. vodka, gin)", "Frutas de estación", "Hierbas aromáticas", "Jarabes artesanales"],
    allergens: [],
    dietary: [],
    calories: 180,
    prepTime: "5-7 min",
    chef_special: true,
  },
  {
    id: "capriccio-cocktail",
    name: "Capriccio",
    description: "Cóctel signature refrescante con toques mediterráneos de romero y naranja, evocando la brisa marina.",
    price: 6990,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=500&h=400&fit=crop",
    ingredients: ["Base de licor (ej. ron, pisco)", "Cítricos", "Especias mediterráneas (ej. romero)", "Jarabe de naranja"],
    allergens: [],
    dietary: [],
    calories: 190,
    prepTime: "5-7 min",
    chef_special: true,
  },

  // Cocteleria
  {
    id: "sour",
    name: "Sour",
    description: "Clásico cóctel sour, perfectamente equilibrado con pisco o whisky, jugo de limón fresco, azúcar y un toque de amargo de angostura.",
    price: 5000,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500&h=400&fit=crop",
    ingredients: ["Pisco o whisky", "Jugo de limón", "Azúcar", "Clara de huevo", "Amargo de angostura"],
    allergens: ["Huevos"],
    dietary: [],
    calories: 150,
    prepTime: "3-5 min",
    popular: true,
  },
  {
    id: "piccione",
    name: "Piccione",
    description: "Cóctel refrescante a base de vodka con vibrantes notas cítricas y un sutil toque de menta, ideal para el verano.",
    price: 6290,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=500&h=400&fit=crop",
    ingredients: ["Base de vodka", "Cítricos frescos", "Toque de menta"],
    allergens: [],
    dietary: ["vegan"],
    calories: 170,
    prepTime: "5 min",
  },
  {
    id: "espresso-martini",
    name: "Espresso Martini",
    description: "Intenso y sofisticado cóctel con vodka, café espresso recién hecho y licor de café, perfecto para los amantes del café.",
    price: 5000,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1575023782549-62ca0d244b39?w=500&h=400&fit=crop",
    ingredients: ["Vodka", "Espresso", "Licor de café", "Azúcar"],
    allergens: [],
    dietary: ["vegan"],
    calories: 220,
    prepTime: "3-5 min",
    popular: true,
  },
  {
    id: "limoncello-spritz",
    name: "Limoncello Spritz",
    description: "Refrescante spritz con el auténtico limoncello italiano, prosecco y agua con gas, decorado con una rodaja de limón.",
    price: 5000,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1608270586620-248524c67de9?w=500&h=400&fit=crop",
    ingredients: ["Limoncello", "Prosecco", "Agua con gas", "Rodaja de limón"],
    allergens: [],
    dietary: ["vegan"],
    calories: 140,
    prepTime: "3 min",
  },
  {
    id: "old-fashioned",
    name: "Old Fashioned",
    description: "El clásico cóctel con whisky bourbon, azúcar, amargo de angostura y un twist de naranja, una bebida atemporal.",
    price: 5000,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=500&h=400&fit=crop",
    ingredients: ["Whisky bourbon", "Azúcar", "Amargo de angostura", "Naranja"],
    allergens: [],
    dietary: ["vegan"],
    calories: 180,
    prepTime: "5 min",
  },
  {
    id: "ramazzoti-spritz",
    name: "Ramazzoti Spritz",
    description: "Spritz italiano vibrante con Ramazzotti, prosecco, agua con gas y una rodaja de naranja, ideal para el aperitivo.",
    price: 5000,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=500&h=400&fit=crop",
    ingredients: ["Ramazzotti", "Prosecco", "Agua con gas", "Naranja"],
    allergens: [],
    dietary: ["vegan"],
    calories: 150,
    prepTime: "3 min",
  },
  {
    id: "martini-sporco",
    name: "Martini Sporco",
    description: "Martini clásico con un toque 'sucio' de salmuera de aceitunas, preparado con gin o vodka y vermut seco, decorado con aceitunas.",
    price: 5000,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1575650775512-ae89114c45dd?w=500&h=400&fit=crop",
    ingredients: ["Gin o vodka", "Vermut seco", "Salmuera de aceitunas", "Aceitunas"],
    allergens: [],
    dietary: ["vegan"],
    calories: 160,
    prepTime: "3-5 min",
  },
  {
    id: "negroni",
    name: "Negroni",
    description: "El clásico cóctel italiano, una mezcla audaz de gin, Campari y vermut rojo, adornado con una rodaja de naranja.",
    price: 5000,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1609951651556-5334e2706168?w=500&h=400&fit=crop",
    ingredients: ["Gin", "Campari", "Vermut rojo", "Naranja"],
    allergens: [],
    dietary: ["vegan"],
    calories: 190,
    prepTime: "3-5 min",
    popular: true,
  },
  {
    id: "gin-tonic",
    name: "Gin Tonic",
    description: "El clásico refrescante con gin premium, agua tónica y un toque de limón o pepino, realzado con hierbas aromáticas.",
    price: 5000,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1587223962930-cb7f31384c19?w=500&h=400&fit=crop",
    ingredients: ["Gin premium", "Agua tónica", "Limón o pepino", "Hierbas aromáticas"],
    allergens: [],
    dietary: ["vegan"],
    calories: 140,
    prepTime: "3 min",
  },

  // Platos Frios
  {
    id: "ceviche-pacifico",
    name: "Ceviche del Pacífico",
    description: "Cubos de atún fresco marinados al estilo leche de tigre, con cítricos, pasta de ají y jengibre, coronados con finas láminas de palta y chips de plátano verde para aportar textura. Una explosión de frescura y sabor del mar.",
    price: 16990,
    category: "appetizers",
    image: "https://images.unsplash.com/photo-1535399831218-d5bd36d1a6b3?w=500&h=400&fit=crop",
    ingredients: ["Atún fresco", "Leche de tigre", "Cítricos", "Pasta de ají", "Jengibre", "Palta", "Chips de plátano verde"],
    allergens: ["Pescado"],
    dietary: ["gluten-free"],
    calories: 280,
    prepTime: "15-20 min",
    chef_special: true,
  },

  // Tapas y Bruschettas
  {
    id: "bruschetta-picante-golfo",
    name: "Bruschetta Picante del Golfo",
    description: "Camarones ecuatorianos salteados con un toque de ají, servidos sobre patacón de plátano verde y toques de limón y cilantro.",
    price: 9990,
    category: "appetizers",
    image: "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=500&h=400&fit=crop",
    ingredients: ["Camarones ecuatorianos", "Ají", "Patacón de plátano verde", "Limón", "Cilantro"],
    allergens: ["Mariscos"],
    dietary: ["gluten-free"],
    calories: 220,
    prepTime: "10-12 min",
    popular: true,
  },

  // Tablas
  {
    id: "tabla-fuego-brasa",
    name: "Tabla de Fuego y Brasa",
    description: "Un festín de cortes: Costillar a la olla, truto de pollo al arrostro, cerdo a la plancha sobre una base de papas rústicas. Ideal para 4 personas, flambeado y acompañado de chimichurri casero.",
    price: 28990,
    category: "main_courses",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=500&h=400&fit=crop",
    ingredients: ["Costillar", "Pollo", "Cerdo", "Papas rústicas", "Chimichurri casero"],
    allergens: [],
    dietary: [],
    calories: 980,
    prepTime: "25-30 min",
    chef_special: true,
  },
  {
    id: "tabla-mediterranea-fria",
    name: "Tabla Mediterránea Fría",
    description: "Selección de charcutería y quesos curados, acompañada de encurtidos caseros, pan rústico de la casa, frutas de estación y frutos secos. Ideal para 2 personas y disfrutar con vino.",
    price: 13990,
    category: "main_courses",
    image: "https://images.unsplash.com/photo-1541345032-c33c8e2cc0c5?w=500&h=400&fit=crop",
    ingredients: ["Charcutería", "Quesos curados", "Encurtidos caseros", "Pan rústico", "Frutas de estación", "Frutos secos"],
    allergens: ["Gluten", "Lácteos", "Frutos secos"],
    dietary: [],
    calories: 650,
    prepTime: "10 min",
    popular: true,
  },

  // Papas Topping
  {
    id: "papas-bufalo",
    name: "Papas Búfalo",
    description: "Papas rústicas salteadas en pasta de ají con especias, un acompañamiento picante y delicioso.",
    price: 9990,
    category: "side_dishes",
    image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=500&h=400&fit=crop",
    ingredients: ["Papas rústicas", "Pasta de ají", "Especias"],
    allergens: [],
    dietary: ["vegan", "gluten-free"],
    calories: 320,
    prepTime: "10-12 min",
    popular: true,
  },

  // Destilados
  {
    id: "gin-tanqueray-london",
    name: "Gin Tanqueray London Dry",
    description: "Gin premium London Dry, perfecto para un gin tonic clásico.",
    price: 6990,
    category: "spirits",
    image: "https://images.unsplash.com/photo-1608885898946-27b461c42e48?w=500&h=400&fit=crop",
    ingredients: ["Gin Tanqueray London Dry"],
    allergens: [],
    dietary: ["vegan"],
    calories: 70,
    prepTime: "1 min",
  },
  {
    id: "whiskey-ballentines",
    name: "Whiskey Ballentines Bourbon 7 años",
    description: "Whiskey bourbon añejado por 7 años, suave y con carácter.",
    price: 4990,
    category: "spirits",
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=500&h=400&fit=crop",
    ingredients: ["Whiskey Ballentines Bourbon"],
    allergens: [],
    dietary: ["vegan"],
    calories: 70,
    prepTime: "1 min",
  },
  {
    id: "whiskey-johnnie-double-black",
    name: "Whiskey Johnnie Walker Double Black",
    description: "Whiskey escocés premium Double Black, con un sabor ahumado intenso y profundo.",
    price: 12990,
    category: "spirits",
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=500&h=400&fit=crop",
    ingredients: ["Whiskey Johnnie Walker Double Black"],
    allergens: [],
    dietary: ["vegan"],
    calories: 70,
    prepTime: "1 min",
  },
  {
    id: "gin-tanqueray-sevilla",
    name: "Gin Tanqueray Sevilla",
    description: "Gin con un distintivo sabor a naranjas de Sevilla, ideal para cócteles cítricos.",
    price: 7990,
    category: "spirits",
    image: "https://images.unsplash.com/photo-1608885898946-27b461c42e48?w=500&h=400&fit=crop",
    ingredients: ["Gin Tanqueray Sevilla"],
    allergens: [],
    dietary: ["vegan"],
    calories: 70,
    prepTime: "1 min",
  },
  {
    id: "gin-tanqueray-royal",
    name: "Gin Tanqueray Royal",
    description: "Gin premium Royal, con un perfil de sabor único y sofisticado.",
    price: 6990,
    category: "spirits",
    image: "https://images.unsplash.com/photo-1608885898946-27b461c42e48?w=500&h=400&fit=crop",
    ingredients: ["Gin Tanqueray Royal"],
    allergens: [],
    dietary: ["vegan"],
    calories: 70,
    prepTime: "1 min",
  },
  {
    id: "tequila-don-julio",
    name: "Tequila Don Julio",
    description: "Tequila premium mexicano, suave y de alta calidad, perfecto para degustar solo o en cócteles.",
    price: 8490,
    category: "spirits",
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=500&h=400&fit=crop",
    ingredients: ["Tequila Don Julio"],
    allergens: [],
    dietary: ["vegan"],
    calories: 65,
    prepTime: "1 min",
  },
  {
    id: "chivas-regal-12",
    name: "Chivas Regal 12 Años",
    description: "Whiskey escocés de 12 años, suave y equilibrado, con notas de miel y frutas.",
    price: 7990,
    category: "spirits",
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=500&h=400&fit=crop",
    ingredients: ["Chivas Regal 12 años"],
    allergens: [],
    dietary: ["vegan"],
    calories: 70,
    prepTime: "1 min",
  },
  {
    id: "whiskey-johnnie-black",
    name: "Whiskey Johnnie Walker Black",
    description: "Whiskey escocés Black Label, un blend rico y complejo con notas de frutas oscuras y vainilla.",
    price: 8990,
    category: "spirits",
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=500&h=400&fit=crop",
    ingredients: ["Whiskey Johnnie Walker Black"],
    allergens: [],
    dietary: ["vegan"],
    calories: 70,
    prepTime: "1 min",
  },
  {
    id: "whiskey-jack-daniel-apple",
    name: "Whiskey Jack Daniel Apple",
    description: "Whiskey con un refrescante sabor a manzana verde, ideal para mezclar o disfrutar con hielo.",
    price: 7990,
    category: "spirits",
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=500&h=400&fit=crop",
    ingredients: ["Whiskey Jack Daniel Apple"],
    allergens: [],
    dietary: ["vegan"],
    calories: 75,
    prepTime: "1 min",
  },
  {
    id: "gin-beefeater",
    name: "Gin Beefeater",
    description: "Gin inglés clásico, con un perfil de sabor audaz y enebro prominente.",
    price: 6990,
    category: "spirits",
    image: "https://images.unsplash.com/photo-1608885898946-27b461c42e48?w=500&h=400&fit=crop",
    ingredients: ["Gin Beefeater"],
    allergens: [],
    dietary: ["vegan"],
    calories: 70,
    prepTime: "1 min",
  },
  {
    id: "jagermeister",
    name: "Jägermeister",
    description: "Licor de hierbas alemán, con una mezcla única de 56 botánicos, ideal para shots fríos.",
    price: 6990,
    category: "spirits",
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=500&h=400&fit=crop",
    ingredients: ["Jägermeister"],
    allergens: [],
    dietary: ["vegan"],
    calories: 80,
    prepTime: "1 min",
  },
  {
    id: "drambuie",
    name: "Drambuie",
    description: "Licor escocés de whisky y miel, con hierbas aromáticas y especias, de sabor dulce y complejo.",
    price: 6990,
    category: "spirits",
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=500&h=400&fit=crop",
    ingredients: ["Drambuie"],
    allergens: [],
    dietary: [],
    calories: 85,
    prepTime: "1 min",
  },
  {
    id: "ron-havana-7",
    name: "Ron Havana Añejo 7 Años",
    description: "Ron cubano añejado por 7 años, con notas de cacao, vainilla y tabaco, perfecto para cócteles o solo.",
    price: 8990,
    category: "spirits",
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=500&h=400&fit=crop",
    ingredients: ["Ron Havana 7 años"],
    allergens: [],
    dietary: ["vegan"],
    calories: 65,
    prepTime: "1 min",
  },
  {
    id: "ron-havana-especial",
    name: "Ron Havana Añejo Especial",
    description: "Ron cubano añejo especial, suave y versátil, ideal para mezclar en tus cócteles favoritos.",
    price: 5990,
    category: "spirits",
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=500&h=400&fit=crop",
    ingredients: ["Ron Havana Añejo Especial"],
    allergens: [],
    dietary: ["vegan"],
    calories: 65,
    prepTime: "1 min",
  },
  {
    id: "pisco-gobernador",
    name: "Pisco El Gobernador",
    description: "Pisco chileno premium, destilado de uvas moscatel, con un sabor suave y aromático.",
    price: 5990,
    category: "spirits",
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=500&h=400&fit=crop",
    ingredients: ["Pisco El Gobernador"],
    allergens: [],
    dietary: ["vegan"],
    calories: 60,
    prepTime: "1 min",
  },
  {
    id: "whisky-johnnie-red",
    name: "Whisky Johnnie Walker Red",
    description: "Whisky escocés Red Label, un blend vibrante y versátil, ideal para mezclar.",
    price: 6990,
    category: "spirits",
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=500&h=400&fit=crop",
    ingredients: ["Whisky Johnnie Walker Red"],
    allergens: [],
    dietary: ["vegan"],
    calories: 70,
    prepTime: "1 min",
  },
  {
    id: "pisco-alto-carmen",
    name: "Pisco Alto del Carmen",
    description: "Pisco chileno tradicional, elaborado con uvas moscatel, de sabor suave y equilibrado.",
    price: 5990,
    category: "spirits",
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=500&h=400&fit=crop",
    ingredients: ["Pisco Alto del Carmen"],
    allergens: [],
    dietary: ["vegan"],
    calories: 60,
    prepTime: "1 min",
  },
  {
    id: "pisco-mistral-nobel",
    name: "Pisco Mistral Nobel",
    description: "Pisco chileno Nobel, de alta gama, con un proceso de añejamiento que le otorga suavidad y complejidad.",
    price: 6990,
    category: "spirits",
    image: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=500&h=400&fit=crop",
    ingredients: ["Pisco Mistral Nobel"],
    allergens: [],
    dietary: ["vegan"],
    calories: 60,
    prepTime: "1 min",
  },
  {
    id: "gin-hendricks",
    name: "Gin Hendrik's",
    description: "Gin escocés con un toque distintivo de pepino y rosas, ideal para un gin tonic floral y refrescante.",
    price: 7990,
    category: "spirits",
    image: "https://images.unsplash.com/photo-1608885898946-27b461c42e48?w=500&h=400&fit=crop",
    ingredients: ["Gin Hendrik's"],
    allergens: [],
    dietary: ["vegan"],
    calories: 70,
    prepTime: "1 min",
  },

  // Vinos y Espumantes
  {
    id: "chardon-rose-187",
    name: "Chardon Rose 187 cc",
    description: "Espumante rosé en formato personal de 187 cc, ideal para celebrar momentos especiales.",
    price: 5500,
    category: "wines",
    image: "https://images.unsplash.com/photo-1547595628-c61a29f496f0?w=500&h=400&fit=crop",
    ingredients: ["Espumante Chardon Rose"],
    allergens: ["Sulfitos"],
    dietary: ["vegan"],
    calories: 85,
    prepTime: "1 min",
  },
  {
    id: "chardon-brut-750",
    name: "Chardon brut 750 cc",
    description: "Espumante brut en botella completa de 750 cc, perfecto para compartir y brindar.",
    price: 16990,
    category: "wines",
    image: "https://images.unsplash.com/photo-1547595628-c61a29f496f0?w=500&h=400&fit=crop",
    ingredients: ["Espumante Chardon Brut"],
    allergens: ["Sulfitos"],
    dietary: ["vegan"],
    calories: 85,
    prepTime: "1 min",
    popular: true,
  },
  {
    id: "viu-manent-noble",
    name: "Viu Manent Noble Semillon Chardonnay",
    description: "Vino dulce noble de cosecha tardía, con notas de frutas maduras y miel, ideal para postres.",
    price: 9990,
    category: "wines",
    image: "https://images.unsplash.com/photo-1547595628-c61a29f496f0?w=500&h=400&fit=crop",
    ingredients: ["Vino Viu Manent Noble"],
    allergens: ["Sulfitos"],
    dietary: ["vegan"],
    calories: 120,
    prepTime: "1 min",
  },
]